### ISSUE TITLE
Add support for HasMetadata/KubernetesResource to all root resources

### ISSUE THREAD

**Issue by bjartek** [teyckmans/kuberig-dsl#13]
All root kubernetes Resources share some common things. 

- apiVersion: Some resources support different apiGroups, not sure how kuberig-dsl does this, if it packages them in different packages. If it does this can be immutable

- kind: This is immutable

- metadata: Most of the fields here are shared. Some non namespaced resources has a different Metamodel since they do not have the namespace attribute.

Suggested hierarchy

```
KubernetesResource:
 - apiVersion
 - kind
 - Metadata

KubernetesNamespacedResource : KubernetesResource
 - NamespacedMetadata instead of Metadata

Metadata:
 - name
 - labels
 - annotations
 -....

NamespacedMetadata : Metadata
 - namespace
```

Inspiration: https://www.javadoc.io/doc/io.fabric8/kubernetes-model/2.0.2/io/fabric8/kubernetes/api/model/HasMetadata.html

Reasoning:

- If working on a collection of objects it would be very nice to make it generic on NamespacedResource, GlobalResource or just Resource

**Comment by bjartek** [comment]
On second though it might be that a namespace object in openapi has the exact same Metadata reference as say a Pod. If it does then the hierarchy above can be simplified a lot.

**Comment by teyckmans** [comment]
Hi Bjarte, yes they share the same io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta.

So we can reduce it to KubernetesResource to get started.

The fact whether a resource is namespaced or not might be detectable by the urls that are in the api spec.
